# Generated by Django 3.1.7 on 2021-07-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('READING', 'Reading'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('PLAN_TO_READ', 'Plan to read')], default='READING', max_length=15),
        ),
    ]
