# Generated by Django 3.1.7 on 2021-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210704_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgender',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='bookgender',
            unique_together={('user', 'name')},
        ),
    ]
